### ISSUE TITLE
Migrate to @grpc/grpc-js

### ISSUE THREAD

**Issue by jsanchez-innomius** [blokur/grpc-ts-demo#2]
Your example has been super helpful, have you consider to create a new example to migrate from grpc to @grpc/grpc-js since grpc will be deprecated the next year and it is not longer accepting any new features? I have tried but i can't not make it work, I can't use the service interface and also i am not able to add a service.

Thank you, regards.

**Comment by BrowduesMan85** [comment]
I have had similar issues. In fact, if I don't use your yarn.lock file, I'm not able to generate code from the proto. 

Speaking for myself and apparently others, 'twould be extremely awesome if you could get this working 🙏

**Comment by mschristensen** [comment]
Thanks @BrowduesMan85 for raising. I've now upgraded from `grpc` to `@grpc/grpc-js` along with v3 of `grpc_tools_node_protoc_ts`.

When there's time in the future I may align with the latest version of `@grpc/grpc-js` and v5 `grpc_tools_node_protoc_ts`, but hopefully this helps in the meantime.
